sudo: required
language: java

services:
  - docker

before_install:
  - mvn -N io.takari:maven:wrapper
  - mvn clean package

install:

before_script:

script:
  - docker build -t cyjay96/pipeline-test .

after_script:

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cyjay96/pipeline-test

after_failure:


