version: '3.3'

services:
  pipeline-test:
    build:
      dockerfile: Dockerfile
      context: ./
    image: cyjay96/pipeline-test
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pipeline_test_db
    networks:
      - postgres-network
    restart: unless-stopped

  postgres:
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pipeline_test_db
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
